[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'
on_if = '!exists("g:vscode")'

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTree', 'NERDTreeToggle', 'NERDTreeFind', 'NERDTreeFocus']

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
on_cmd = ['IndentGuidesEnable', 'IndentGuidesToggle']

[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = 'Vinarise'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_event = 'InsertEnter'
on_if = '!exists("g:vscode") && &ft == "python"'
