[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'nixprime/cpsm'

[[plugins]]
repo = 'neoclide/coc.nvim'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
  let g:ale_enabled = 1
  let g:ale_completion_enabled = 0
  let g:ale_disable_lsp = 1
  let g:ale_sign_column_always = 1

  augroup ale
    autocmd!
    autocmd BufEnter * let b:ale_enabled = &modifiable
  augroup END
'''

[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
  let g:surround_no_mappings = 1
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'dracula/vim'
name = 'dracula'
