[[plugins]]
repo = 'Shougo/deoplete.nvim'
hook_add = 'let g:deoplete#enable_at_startup = 1'
on_i = 1

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_source = 'deoplete.nvim'
on_ft = 'python'

#[[plugins]]
#repo = 'cohama/lexima.vim'
#on_i = 1

#[[plugins]]
#repo = 'Vimjas/vim-python-pep8-indent'
#on_ft = ['python']
# on_i = 1

