[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'
on_if = '!exists("g:vscode")'

[[plugins]]
repo = 'vim-skk/eskk.vim'
on_event = ['InsertEnter', 'CmdlineEnter']
on_if = '!exists("g:vscode")'
hook_add = '''
  let g:eskk#directory = expand('~/.config/eskk')
  let g:eskk#dictionary = {
  \    'path': expand('~/.config/eskk/user.dict'),
  \    'sorted': 1,
  \    'encoding': 'utf-8',
  \ }

  let s:nix_large_dictionary_path = expand('~/.config/skk/SKK-JISYO.nix.utf8')
  if filereadable(s:nix_large_dictionary_path)
    let s:large_dictionary_path = s:nix_large_dictionary_path
  else
    let s:large_dictionary_path = expand('~/.config/skk/SKK-JISYO.merged.utf8')
  endif

  let g:eskk#large_dictionary = {
  \    'path': s:large_dictionary_path,
  \    'sorted': 1,
  \    'encoding': 'utf-8',
  \ }

  let g:eskk#egg_like_newline = 1
  let g:eskk#show_annotation = 1
  let g:eskk#enable_completion = 0
  let g:eskk#dont_map_default_if_already_mapped = 0
  imap jk <Plug>(eskk:toggle)
  cmap jk <Plug>(eskk:toggle)
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
on_cmd = 'QuickRun'

[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTree', 'NERDTreeToggle', 'NERDTreeFind', 'NERDTreeFocus']

[[plugins]]
repo = 'APZelos/blamer.nvim'
on_cmd = ['BlamerHide', 'BlamerShow', 'BlamerToggle']
hook_add = '''
  let g:blamer_enabled = 1
  let g:blamer_delay = 100
'''

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
on_cmd = ['IndentGuidesEnable', 'IndentGuidesToggle']

[[plugins]]
repo = 'Shougo/vinarise.vim'
on_cmd = 'Vinarise'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_event = 'InsertEnter'
on_if = '!exists("g:vscode") && &ft == "python"'
