[[plugins]]
repo = 'Shougo/dein.vim'

#[[plugins]]
#repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'w0rp/ale'

#[[plugins]]
#repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
repo = "airblade/vim-gitgutter"

[[plugins]]
repo = "tpope/vim-fugitive"

[[plugins]]
repo = 'Shougo/vinarise.vim'

