[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
on_if = '!exists("g:vscode")'

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim") && !exists("g:vscode")'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim") && !exists("g:vscode")'

[[plugins]]
repo = 'nixprime/cpsm'
on_if = '!exists("g:vscode")'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'
on_if = '!exists("g:vscode")'

[[plugins]]
repo = 'neoclide/coc.nvim'
on_if = '!exists("g:vscode")'

[[plugins]]
repo = 'w0rp/ale'
on_if = '!exists("g:vscode")'
hook_add = '''
  let g:ale_enabled = 1
  let g:ale_completion_enabled = 0
  let g:ale_disable_lsp = 1
  let g:ale_sign_column_always = 1

  augroup ale
    autocmd!
    autocmd BufEnter * let b:ale_enabled = &modifiable
  augroup END
'''

[[plugins]]
repo = 'tpope/vim-surround'
hook_add = '''
  let g:surround_no_mappings = 1
  nmap ds     <Plug>Dsurround
  nmap cs     <Plug>Csurround
  nmap cS     <Plug>CSurround
  nmap ys     <Plug>Ysurround
  nmap yS     <Plug>YSurround
  nmap yss    <Plug>Yssurround
  nmap ySs    <Plug>YSsurround
  nmap ySS    <Plug>YSsurround
  xmap ys     <Plug>VSurround
  xmap yS     <Plug>VgSurround
  imap <C-S>  <Plug>Isurround
  imap <C-G>s <Plug>Isurround
  imap <C-G>S <Plug>ISurround
'''

[[plugins]]
repo = 'puremourning/vimspector'
on_if = '!exists("g:vscode")'
hook_add = '''
  let g:vimspector_base_dir = expand('~/.config/vimspector')
  let g:vimspector_enable_mappings = 'VISUAL_STUDIO'
  let g:vimspector_sign_priority = {
  \    'vimspectorBP':         999,
  \    'vimspectorBPCond':     999,
  \    'vimspectorBPDisabled': 999,
  \ }
  nmap <C-q>   <Plug>VimspectorBalloonEval
  xmap <C-q>   <Plug>VimspectorBalloonEval
  nmap <C-F9>  <Plug>VimspectorToggleConditionalBreakpoint
  nmap <F8>    <Plug>VimspectorRunToCursor
  nnoremap <silent> <C-F5>  :<C-u>VimspectorReset<CR>
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_if = '!exists("g:vscode")'

[[plugins]]
repo = 'Shougo/context_filetype.vim'
on_if = '!exists("g:vscode")'

[[plugins]]
repo = 'osyo-manga/vim-precious'
on_if = '!exists("g:vscode")'

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_if = '!exists("g:vscode")'

[[plugins]]
repo = 'tpope/vim-fugitive'
on_if = '!exists("g:vscode")'

[[plugins]]
repo = 'dracula/vim'
name = 'dracula'
on_if = '!exists("g:vscode")'
