import = ["~/.config/alacritty/colors/ubuntu_dark.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
blink_interval = 750
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "None"

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 11.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "monospace"

[font.offset]
x = 0
y = -1

[scrolling]
history = 50000
multiplier = 3

[window]
dynamic_padding = false
dynamic_title = true
decorations_theme_variant = "None"
opacity = 0.9
startup_mode = "Maximized"
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[window.position]
x = 110
y = 110
